[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
svault = "7TvoaiWggkJ5hz69s3pvVEJ17uADX4uuEYuidbYDnFHu"
vault = "8uRuVNnQ6VED2ByozMkgnPBSUG9MNgVdHut1WhJvThTf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
